#!/bin/bash


# #%# capabilities=autoconf
# #%# family=contrib


cpu_num="$(nproc)"  # depends on coreutils
base="/sys/devices/system/cpu/"

case $1 in
    config)
        echo "graph_title CPU Frequencies"
        echo "graph_info Show CPU frequencies"
        echo "graph_vlabel frequency [Hz]"
        echo "graph_category system"

        for ((i=0;i<=cpu_num-1;i++)); do
            echo "cpu$i.label CPU $((i+1))"
            echo "cpu$i.min $(cat $base/cpu$i/cpufreq/cpuinfo_min_freq)"
            echo "cpu$i.max $(cat $base/cpu$i/cpufreq/cpuinfo_max_freq)"
        done

        max_freq=$(cat $base/cpu0/cpufreq/cpuinfo_max_freq)
        echo "graph_args --base 1000 -l 0 -u $max_freq"

        exit 0
    ;;
    autoconf)
        if [ -r "$base/cpu0/cpufreq/scaling_cur_freq" ]; then
            echo yes
        else
            echo "no (no frequency information found)"
        fi
        exit 0
    ;;
esac


for ((i=0;i<=cpu_num-1;i++)); do
    val="$(cat $base/cpu$i/cpufreq/scaling_cur_freq)"
    echo "cpu$i.value $val"
done
