#!/bin/bash


# #%# capabilities=autoconf
# #%# family=contrib


proc_num=${process_number:-5}

case $1 in
    config)
        echo "graph_title Process CPU usage"
        echo "graph_info Show CPU usage of most intensive processes"
        echo 'graph_vlabel %'
        echo 'graph_scale no'
        echo "graph_category processes"
        echo "graph_args --base 1000 -l 0 -r"

        for ((i=0;i<=proc_num-1;i++)); do
            echo "proc$i.label Process #$((i+1))"
            echo "proc$i.warning 95"
        done

        exit 0
    ;;
    autoconf)
        echo yes
        exit 0
    ;;
esac


proc_list=$(ps axo 'pcpu' | tail -n +2 | sort -rh | head -n $proc_num)  # ,comm

i=0
while read proc_cpu; do
    echo "proc$i.value $proc_cpu"
    i=$((i+1))
done <<< "$proc_list"
